apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    Bar: baz
    Foo: ""
    KubeApiVersion: ""
    KubeVersion: ""
    argocd.argoproj.io/tracking-id: my-app-uat:/ConfigMap:/my-app-uat
  name: my-app-uat
  namespace: ""
